# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 539)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.agentsButton = QtWidgets.QToolButton(self.centralwidget)
        self.agentsButton.setMinimumSize(QtCore.QSize(0, 35))
        self.agentsButton.setIcon(icon)
        self.agentsButton.setIconSize(QtCore.QSize(24, 24))
        self.agentsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.agentsButton.setObjectName("agentsButton")
        self.horizontalLayout_3.addWidget(self.agentsButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.createTaskButton = QtWidgets.QToolButton(self.centralwidget)
        self.createTaskButton.setMinimumSize(QtCore.QSize(0, 35))
        self.createTaskButton.setSizeIncrement(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createTaskButton.setIcon(icon1)
        self.createTaskButton.setIconSize(QtCore.QSize(24, 24))
        self.createTaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.createTaskButton.setObjectName("createTaskButton")
        self.horizontalLayout_3.addWidget(self.createTaskButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.tasksButton = QtWidgets.QToolButton(self.centralwidget)
        self.tasksButton.setMinimumSize(QtCore.QSize(0, 35))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/file (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tasksButton.setIcon(icon2)
        self.tasksButton.setIconSize(QtCore.QSize(24, 24))
        self.tasksButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tasksButton.setObjectName("tasksButton")
        self.horizontalLayout_3.addWidget(self.tasksButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.resultsButton = QtWidgets.QToolButton(self.centralwidget)
        self.resultsButton.setMinimumSize(QtCore.QSize(0, 35))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsButton.setIcon(icon3)
        self.resultsButton.setIconSize(QtCore.QSize(24, 24))
        self.resultsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.resultsButton.setObjectName("resultsButton")
        self.horizontalLayout_3.addWidget(self.resultsButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.agents = QtWidgets.QWidget()
        self.agents.setObjectName("agents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.agents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.agents)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.agentsComboBox = QtWidgets.QComboBox(self.agents)
        self.agentsComboBox.setMinimumSize(QtCore.QSize(350, 28))
        self.agentsComboBox.setObjectName("agentsComboBox")
        self.horizontalLayout_6.addWidget(self.agentsComboBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.agents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hardwarePlainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.hardwarePlainTextEdit.setAutoFillBackground(False)
        self.hardwarePlainTextEdit.setReadOnly(True)
        self.hardwarePlainTextEdit.setBackgroundVisible(False)
        self.hardwarePlainTextEdit.setObjectName("hardwarePlainTextEdit")
        self.verticalLayout_5.addWidget(self.hardwarePlainTextEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_packages = QtWidgets.QWidget()
        self.tab_packages.setObjectName("tab_packages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_packages)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.softwarePlainTextEdit = QtWidgets.QPlainTextEdit(self.tab_packages)
        self.softwarePlainTextEdit.setReadOnly(True)
        self.softwarePlainTextEdit.setObjectName("softwarePlainTextEdit")
        self.verticalLayout_4.addWidget(self.softwarePlainTextEdit)
        self.tabWidget.addTab(self.tab_packages, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.agents)
        self.create_task = QtWidgets.QWidget()
        self.create_task.setObjectName("create_task")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.create_task)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.create_task)
        self.label_3.setMinimumSize(QtCore.QSize(85, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.taskNameEdit = QtWidgets.QLineEdit(self.create_task)
        self.taskNameEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.taskNameEdit.setObjectName("taskNameEdit")
        self.horizontalLayout_9.addWidget(self.taskNameEdit)
        spacerItem9 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.saveTaskButton = QtWidgets.QToolButton(self.create_task)
        self.saveTaskButton.setMinimumSize(QtCore.QSize(0, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveTaskButton.setIcon(icon4)
        self.saveTaskButton.setIconSize(QtCore.QSize(20, 20))
        self.saveTaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.saveTaskButton.setAutoRaise(False)
        self.saveTaskButton.setObjectName("saveTaskButton")
        self.horizontalLayout_9.addWidget(self.saveTaskButton)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.clearTaskButton = QtWidgets.QToolButton(self.create_task)
        self.clearTaskButton.setMinimumSize(QtCore.QSize(0, 32))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/cleaner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearTaskButton.setIcon(icon5)
        self.clearTaskButton.setIconSize(QtCore.QSize(20, 20))
        self.clearTaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.clearTaskButton.setObjectName("clearTaskButton")
        self.horizontalLayout_9.addWidget(self.clearTaskButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        spacerItem12 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.create_task)
        self.label_4.setMinimumSize(QtCore.QSize(85, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.taskCategoryComboBox = QtWidgets.QComboBox(self.create_task)
        self.taskCategoryComboBox.setMinimumSize(QtCore.QSize(350, 28))
        self.taskCategoryComboBox.setObjectName("taskCategoryComboBox")
        self.taskCategoryComboBox.addItem("")
        self.taskCategoryComboBox.addItem("")
        self.taskCategoryComboBox.addItem("")
        self.taskCategoryComboBox.addItem("")
        self.taskCategoryComboBox.addItem("")
        self.taskCategoryComboBox.addItem("")
        self.taskCategoryComboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.taskCategoryComboBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        spacerItem14 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.create_task)
        self.label_5.setMinimumSize(QtCore.QSize(85, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.taskParameterEdit = QtWidgets.QLineEdit(self.create_task)
        self.taskParameterEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.taskParameterEdit.setObjectName("taskParameterEdit")
        self.horizontalLayout_11.addWidget(self.taskParameterEdit)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem16)
        self.stackedWidget.addWidget(self.create_task)
        self.tasks = QtWidgets.QWidget()
        self.tasks.setObjectName("tasks")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tasks)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tasks)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.tasksComboBox = QtWidgets.QComboBox(self.tasks)
        self.tasksComboBox.setMinimumSize(QtCore.QSize(350, 0))
        self.tasksComboBox.setObjectName("tasksComboBox")
        self.horizontalLayout_7.addWidget(self.tasksComboBox)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.deleteTaskButton = QtWidgets.QToolButton(self.tasks)
        self.deleteTaskButton.setMinimumSize(QtCore.QSize(0, 32))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/delete_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteTaskButton.setIcon(icon6)
        self.deleteTaskButton.setIconSize(QtCore.QSize(20, 20))
        self.deleteTaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.horizontalLayout_7.addWidget(self.deleteTaskButton)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem20 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem20)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.tasks)
        self.label_10.setMinimumSize(QtCore.QSize(90, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.showTaskAgentsComboBox = QtWidgets.QComboBox(self.tasks)
        self.showTaskAgentsComboBox.setMinimumSize(QtCore.QSize(350, 0))
        self.showTaskAgentsComboBox.setObjectName("showTaskAgentsComboBox")
        self.horizontalLayout_4.addWidget(self.showTaskAgentsComboBox)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem21)
        self.executeTaskButton = QtWidgets.QToolButton(self.tasks)
        self.executeTaskButton.setMinimumSize(QtCore.QSize(0, 32))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.executeTaskButton.setIcon(icon7)
        self.executeTaskButton.setIconSize(QtCore.QSize(20, 20))
        self.executeTaskButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.executeTaskButton.setObjectName("executeTaskButton")
        self.horizontalLayout_4.addWidget(self.executeTaskButton)
        spacerItem22 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem22)
        self.execute2AllButton = QtWidgets.QToolButton(self.tasks)
        self.execute2AllButton.setMinimumSize(QtCore.QSize(0, 32))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/multiple_execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.execute2AllButton.setIcon(icon8)
        self.execute2AllButton.setIconSize(QtCore.QSize(20, 20))
        self.execute2AllButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.execute2AllButton.setObjectName("execute2AllButton")
        self.horizontalLayout_4.addWidget(self.execute2AllButton)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem23)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem24 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem24)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.tasks)
        self.label_7.setMinimumSize(QtCore.QSize(90, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.showTaskCategoryEdit = QtWidgets.QLineEdit(self.tasks)
        self.showTaskCategoryEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.showTaskCategoryEdit.setReadOnly(True)
        self.showTaskCategoryEdit.setObjectName("showTaskCategoryEdit")
        self.horizontalLayout_12.addWidget(self.showTaskCategoryEdit)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        spacerItem26 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem26)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tasks)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.showTaskParametersEdit = QtWidgets.QLineEdit(self.tasks)
        self.showTaskParametersEdit.setMinimumSize(QtCore.QSize(500, 0))
        self.showTaskParametersEdit.setObjectName("showTaskParametersEdit")
        self.horizontalLayout_8.addWidget(self.showTaskParametersEdit)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem28)
        self.stackedWidget.addWidget(self.tasks)
        self.results = QtWidgets.QWidget()
        self.results.setObjectName("results")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.results)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem29)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.results)
        self.label_8.setMinimumSize(QtCore.QSize(160, 0))
        self.label_8.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.resultsComboBox = QtWidgets.QComboBox(self.results)
        self.resultsComboBox.setMinimumSize(QtCore.QSize(450, 28))
        self.resultsComboBox.setObjectName("resultsComboBox")
        self.horizontalLayout_2.addWidget(self.resultsComboBox)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem30)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        spacerItem31 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem31)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.results)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.taskStatusLabel = QtWidgets.QLabel(self.results)
        self.taskStatusLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.taskStatusLabel.setText("")
        self.taskStatusLabel.setObjectName("taskStatusLabel")
        self.horizontalLayout_5.addWidget(self.taskStatusLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem32 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem32)
        self.label_9 = QtWidgets.QLabel(self.results)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.resultsTextEdit = QtWidgets.QPlainTextEdit(self.results)
        self.resultsTextEdit.setReadOnly(True)
        self.resultsTextEdit.setObjectName("resultsTextEdit")
        self.verticalLayout_8.addWidget(self.resultsTextEdit)
        self.stackedWidget.addWidget(self.results)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raspberries Remote Management"))
        self.agentsButton.setText(_translate("MainWindow", "Raspberries"))
        self.createTaskButton.setText(_translate("MainWindow", "Δημιουργία Εργασίας"))
        self.tasksButton.setText(_translate("MainWindow", "Εργασίες"))
        self.resultsButton.setText(_translate("MainWindow", "Αποτελέσματα"))
        self.label.setText(_translate("MainWindow", "Raspberry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Χαρακτηριστικά Συστήματος"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_packages), _translate("MainWindow", "Πακέτα Λογισμικού"))
        self.label_3.setText(_translate("MainWindow", "Όνομα"))
        self.saveTaskButton.setText(_translate("MainWindow", "Αποθήκευση"))
        self.clearTaskButton.setText(_translate("MainWindow", "Καθαρισμός"))
        self.label_4.setText(_translate("MainWindow", "Κατηγορία"))
        self.taskCategoryComboBox.setItemText(0, _translate("MainWindow", "Καταγραφή Χαρακτηριστικών "))
        self.taskCategoryComboBox.setItemText(1, _translate("MainWindow", "Καταγραφή Πακέτων Λογισμικού"))
        self.taskCategoryComboBox.setItemText(2, _translate("MainWindow", "Πλήρης Καταγραφή"))
        self.taskCategoryComboBox.setItemText(3, _translate("MainWindow", "Εντολές Συστήματος"))
        self.taskCategoryComboBox.setItemText(4, _translate("MainWindow", "Γενικές Εντολές"))
        self.taskCategoryComboBox.setItemText(5, _translate("MainWindow", "Εγκατάσταση Πακέτου Λογισμικού"))
        self.taskCategoryComboBox.setItemText(6, _translate("MainWindow", "Απεγκατάσταση Πακέτου Λογισμικού"))
        self.label_5.setText(_translate("MainWindow", "Περιγραφή "))
        self.label_2.setText(_translate("MainWindow", "Εργασίες"))
        self.deleteTaskButton.setText(_translate("MainWindow", "Διαγραφή"))
        self.label_10.setText(_translate("MainWindow", "Raspberry"))
        self.executeTaskButton.setText(_translate("MainWindow", "Απλή Εκτέλεση"))
        self.execute2AllButton.setText(_translate("MainWindow", "Πολλαπλή Εκτέλεση"))
        self.label_7.setText(_translate("MainWindow", "Κατηγορία"))
        self.label_6.setText(_translate("MainWindow", "Περιγραφή"))
        self.label_8.setText(_translate("MainWindow", "Εκτελεσμένες Εργασίες"))
        self.label_12.setText(_translate("MainWindow", "Κατάσταση"))
        self.label_9.setText(_translate("MainWindow", "Αποτελέσματα"))
        self.menuHelp.setTitle(_translate("MainWindow", "Βοήθεια"))
        self.actionAbout.setText(_translate("MainWindow", "Σχετικα"))

import management_rc
